ANALYSIS_SCHEMA = {
    "type": "object",
    "required": [
        "meta",
        "summary",
        "timeline",
        "visual_language",
        "rhythm_structure",
        "camera_language",
        "emotion_and_psychology",
        "viral_mechanics",
        "transferable_pattern",
        "seedance_translation",
        "next_step_assets",
    ],
    "properties": {
        "meta": {"type": "object"},
        "summary": {"type": "object"},
        "timeline": {"type": "array"},
        "visual_language": {"type": "object"},
        "rhythm_structure": {"type": "object"},
        "camera_language": {"type": "object"},
        "emotion_and_psychology": {"type": "object"},
        "viral_mechanics": {"type": "object"},
        "transferable_pattern": {"type": "object"},
        "seedance_translation": {"type": "object"},
        "next_step_assets": {"type": "object"},
    },
    "additionalProperties": True,
}
