ANALYSIS_SCHEMA = {
    "type": "object",
    "required": [
        "meta",
        "summary",
        "timeline",
        "visual_language",
        "rhythm_structure",
        "camera_language",
        "emotion_and_psychology",
        "viral_mechanics",
        "transferable_pattern",
        "seedance_translation",
        "next_step_assets",
    ],
    "properties": {
        "meta": {"type": "object"},
        "summary": {"type": "object"},
        "timeline": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "start",
                    "end",
                    "visual_event",
                    "subject_action",
                    "camera_action",
                    "audio_event",
                    "narrative_function",
                    "attention_level",
                ],
                "properties": {
                    "start": {"type": "number"},
                    "end": {"type": "number"},
                    "visual_event": {"type": "string"},
                    "subject_description": {"type": "string"},
                    "subject_action": {"type": "string"},
                    "camera_action": {"type": "string"},
                    "camera_details": {"type": "string"},
                    "lighting_description": {"type": "string"},
                    "environment_description": {"type": "string"},
                    "audio_event": {"type": "string"},
                    "narrative_function": {
                        "type": "string",
                        "enum": ["hook", "setup", "build", "twist", "payoff", "ending"],
                    },
                    "attention_level": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 5,
                    },
                    "color_tone": {"type": "string"},
                },
                "additionalProperties": True,
            },
        },
        "visual_language": {
            "type": "object",
            "properties": {
                "style_keywords": {"type": "array", "items": {"type": "string"}},
                "palette": {"type": "array", "items": {"type": "string"}},
                "lighting": {"type": "array", "items": {"type": "string"}},
                "texture_fx": {"type": "array", "items": {"type": "string"}},
                "environment_traits": {"type": "array", "items": {"type": "string"}},
                "subject_design_traits": {"type": "array", "items": {"type": "string"}},
                "realism_level": {
                    "type": "string",
                    "enum": [
                        "photorealistic",
                        "semi-realistic",
                        "stylized",
                        "3d-render",
                        "anime",
                        "abstract",
                    ],
                },
                "production_look": {"type": "string"},
                "skin_texture": {"type": "string"},
                "camera_equipment_feel": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "rhythm_structure": {"type": "object"},
        "camera_language": {"type": "object"},
        "emotion_and_psychology": {"type": "object"},
        "viral_mechanics": {"type": "object"},
        "transferable_pattern": {"type": "object"},
        "seedance_translation": {"type": "object"},
        "next_step_assets": {"type": "object"},
    },
    "additionalProperties": True,
}
